name: maven.yml
run-name: 'Maven build workflow #${{ github.run_number }} triggered by ${{ github.actor }} on ${{ github.ref }}'

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      has_frontend:
        description: 'Boolean if the module has a frontend'
        required: true
        type: boolean
      java_version:
        required: true
        type: string
    secrets:
      NEXUS3_PW:
        required: true
      NEXUS_NPM_TOKEN_READ_ONLY:
        required: true
      MACDUFF_KEYCHAIN_PASSWORD:
        required: true
      NEXUS_NPM_TOKEN_WRITE:
        required: false
    outputs:
      VERSION:
        description: 'Build version'
        value: ${{ jobs.maven.outputs.VERSION }}
      GROUP_ID:
        description: 'The maven groupId attribute'
        value: ${{ jobs.maven.outputs.GROUP_ID }}
      run_id:
        description: "The run-id of the job that uploaded the build artifact"
        value: ${{ github.run_id }}
      branch_name_slug:
        description: "The slug of the current branch"
        value: ${{ jobs.maven.outputs.branch_name_slug }}

env:
  DOCKER_CONFIG_DIRECTORY: "${{ github.workspace }}/.docker"

jobs:
  maven:
    name: Deploy
    runs-on: macduff
    timeout-minutes: 60
    env:
      CI_AUTH_USR: ${{ vars.NEXUS3_USER }}
      CI_AUTH_PSW: ${{ secrets.NEXUS3_PW }}
      HELM_REGISTRY_CONFIG: "~/.docker/config.json"
    outputs:
      VERSION: ${{ steps.vars.outputs.RC_VERSION }}
      GROUP_ID: ${{ steps.vars.outputs.GROUP_ID }}
      branch_name_slug: ${{ steps.slug.outputs.branch-name-slug }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          # Need to fetch everything, otherwise "spotless-maven-plugin" fails because we reference origin/master branch in the configuration
          fetch-depth: 0

      - name: Setup Variables
        id: vars
        uses: uniport/workflows/.github/actions/setup-maven-build-variables@ci-migration

      - uses: gacts/github-slug@v1
        id: slug

      - name: Disable man-db triggers
        uses: uniport/workflows/.github/actions/disable-man-db-triggers@ci-migration

      - name: Setup Java
        uses: uniport/workflows/.github/actions/setup-java@ci-migration
        with:
          architecture: ${{ contains(runner.name, 'macduff') && 'aarch64' || '' }}
          cache-maven: ${{ !contains(runner.name, 'macduff') }}
          java-version: ${{ inputs.java_version }}

      - name: Unlock keychain
        if: ${{ contains(runner.name, 'macduff') }}
        run: |
          security unlock-keychain -p "${{ secrets.MACDUFF_KEYCHAIN_PASSWORD }}"

      - name: Setup Helm
        uses: uniport/workflows/.github/actions/add-helm-repositories@ci-migration
        with:
          username: ${{ env.CI_AUTH_USR }}
          password: ${{ env.CI_AUTH_PSW }}

      - name: Login to Nexus Docker Registry
        uses: docker/login-action@v3
        with:
          registry: uniportcr.artifacts.inventage.com
          username: ${{ env.CI_AUTH_USR }}
          password: ${{ env.CI_AUTH_PSW }}
          logout: ${{ !contains(runner.name, 'macduff') }}

      - name: Setup NPM Access
        if: ${{ inputs.has_frontend }}
        uses: uniport/workflows/.github/actions/setup-npm-nexus-access@ci-migration
        with:
          token: ${{ secrets.NEXUS_NPM_TOKEN_READ_ONLY }}
          repository: inventage-portal-npm-group
          auth-file: frontend/src/main/web/.npmrc

      - name: Setup NPM Access (staging)
        if: ${{ inputs.has_frontend }}
        uses: uniport/workflows/.github/actions/setup-npm-nexus-access@ci-migration
        with:
          token: ${{ secrets.NEXUS_NPM_TOKEN_WRITE }}
          repository: inventage-portal-npm-staging
          auth-file: frontend/src/main/web/.npmrc

      - name: Set version
        uses: uniport/workflows/.github/actions/set-maven-project-version@ci-migration
        with:
          version: ${{ steps.vars.outputs.RC_VERSION }}
          settings-file: .github/settings.xml
          script: true

      - name: Copy .docker directory
        run: |
          cp -Rpf ~/.docker ${{ env.DOCKER_CONFIG_DIRECTORY }}

      - name: Maven build
        run: |
          mvn -B -V --no-transfer-progress --update-snapshots --settings .github/settings.xml -DmultiArchBuild=true deploy -Ddocker.dockerStateDir=${{ env.DOCKER_CONFIG_DIRECTORY }}
        env:
          PACKAGE_VERSION: ${{ steps.vars.outputs.RC_VERSION }}

      # Needs to run after the build, otherwise some dependencies are missing for maven… ¯\_(ツ)_/¯
      - name: Checkstyle
        run: |
          mvn -B -V --no-transfer-progress --settings .github/settings.xml initialize checkstyle:check

      # Needs to run after the build, otherwise some dependencies are missing for maven… ¯\_(ツ)_/¯
      - name: Spotbugs
        run: |
          mvn -B -V --no-transfer-progress --settings .github/settings.xml initialize spotbugs:check

      - name: Check uncommitted code
        uses: uniport/workflows/.github/actions/ensure-no-uncommitted-code@ci-migration

      - name: Frontend Test Coverage
        if: ${{ inputs.has_frontend }}
        uses: livewing/lcov-job-summary@v1.2.0
        with:
          lcov: frontend/src/main/web/coverage/lcov.info

      - name: Summary
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<EOF
          ## Maven Build
          This workflow ran successfully on **$(date)**.
          ### Outputs
          - **VERSION**: \`${{ steps.vars.outputs.RC_VERSION }}\`
          - **GROUP_ID**: \`${{ steps.vars.outputs.GROUP_ID }}\`
          EOF
