name: Build/Release
run-name: 'Build & release "${{ inputs.component_name }}" (#${{ github.run_number }}) by ${{ github.actor }} on ${{ github.ref_name }}'
  

on:
  workflow_call:
    inputs:
      # === Required ===
      component_name:
        description: 'Component name for deployment and archetype'
        required: true
        type: string
      java_version:
        description: 'Java version used for the build'
        required: true
        type: string

      # === Deployment Options ===
      deploy_to_dev:
        description: 'Deploy to development environment'
        required: false
        type: boolean
        default: true

      # === Frontend ===
      has_frontend:
        description: 'Whether the component includes a frontend'
        required: false
        type: boolean
        default: false

      # === NPM Options ===
      needs_npm_access:
        description: 'If the builds needs to read/write to the npm repo'
        required: false
        type: boolean
        default: false
      npmrc_path:
        description: 'Path to the .npmrc file for NPM authentication'
        required: false
        type: string
        default: 'frontend/src/main/web/.npmrc'

      # === Archetype Options ===
      update_archetype:
        description: 'Update the Uniport archetype after a successful build'
        required: false
        type: boolean
        default: true

      # === Tagging Options ===
      tag_docker:
        description: 'Tag Docker artifacts'
        required: false
        type: boolean
        default: true
      tag_maven:
        description: 'Tag Maven artifacts'
        required: false
        type: boolean
        default: true
      tag_npm:
        description: 'Tag NPM artifacts'
        required: false
        type: boolean
        default: false
      tag_helm:
        description: 'Tag Helm artifacts'
        required: false
        type: boolean
        default: false
    secrets:
      NEXUS3_PW:
        required: true
      NEXUS_NPM_TOKEN_READ_ONLY:
        required: true
      MACDUFF_KEYCHAIN_PASSWORD:
        required: true
      UNIPORT_APP_PRIVATE_KEY:
        required: true
      NEXUS_NPM_TOKEN_WRITE:
        required: false


# Prevent running builds for the same branch in parallel
# New workflows will cancel existing workflows
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  maven:
    name: Maven
    uses: ./.github/workflows/base-maven-build.yml
    with:
      java_version: ${{ inputs.java_version }}
      has_frontend: ${{ inputs.has_frontend }}
      needs_npm_access: ${{ inputs.needs_npm_access }}
      npmrc_path: ${{ inputs.npmrc_path }}
    secrets:
      NEXUS3_PW: ${{ secrets.NEXUS3_PW }}
      NEXUS_NPM_TOKEN_READ_ONLY: ${{ secrets.NEXUS_NPM_TOKEN_READ_ONLY }}
      MACDUFF_KEYCHAIN_PASSWORD: ${{ secrets.MACDUFF_KEYCHAIN_PASSWORD }}
      NEXUS_NPM_TOKEN_WRITE: ${{ secrets.NEXUS_NPM_TOKEN_WRITE }}

  deploy_dev:
    name: Deploy
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || inputs.deploy_to_dev }}
    needs: [maven]
    uses: ./.github/workflows/base-deploy-dev.yml
    with:
      version: ${{ needs.maven.outputs.VERSION }}
      component_name: ${{ inputs.component_name }}
      branch: ${{ inputs.deploy_branch }}
    secrets:
      UNIPORT_APP_PRIVATE_KEY: ${{ secrets.UNIPORT_APP_PRIVATE_KEY }}

  update_archetype:
    name: Update Archetype
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || inputs.update_archetype }}
    needs: [maven]
    uses: ./.github/workflows/base-update-archetype.yml
    with:
      version: ${{ needs.maven.outputs.VERSION }}
      component_name: ${{ inputs.component_name }}
    secrets:
      UNIPORT_APP_PRIVATE_KEY: ${{ secrets.UNIPORT_APP_PRIVATE_KEY }}

  tag_artifacts:
    name: Tag Artifacts
    if: ${{ inputs.tag_docker || inputs.tag_maven || inputs.tag_npm || inputs.tag_helm}}
    needs: [maven]
    uses: ./.github/workflows/base-tag-nexus-artifacts.yml
    with:
      version: ${{ needs.maven.outputs.VERSION }}
      group_id: ${{ needs.maven.outputs.GROUP_ID }}
      tag_docker: ${{ inputs.tag_docker }}
      tag_maven: ${{ inputs.tag_maven }}
      tag_npm: ${{ inputs.tag_npm }}
      tag_helm: ${{ inputs.tag_helm }}
    secrets:
      NEXUS3_PW: ${{ secrets.NEXUS3_PW }}
