# Workflow for creating a git tag
name: Git Tag

on:
  workflow_call:
    inputs:
      tag_name:
        description: 'The tag name'
        type: string
        required: true
      tag_message:
        description: 'The tag message'
        type: string
        required: true
      commit_sha:
        description: 'The commit SHA to create the tag on'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The tag name'
        type: string
        required: true
      tag_message:
        description: 'The tag message'
        type: string
        required: true
      commit_sha:
        description: 'The commit SHA to create the tag on'
        type: string
        required: true

jobs:
  tag:
    name: Create Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write # create git tag
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          # to fetch everything to be able to tag any commit
          ref: ${{ github.ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Configure Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Git Tag
        shell: bash
        run: |
          echo "Running on branch: $(git rev-parse --abbrev-ref HEAD)"

          git tag \
            --annotate "${{ inputs.tag_name }}" \
            --message "${{ inputs.tag_message }}" \
            "${{inputs.commit_sha }}"

      # There's an issue in GitHub where changes cannot be pushed from an action if the tag points to a commit where
      # the contents of .github/workflows/ are not identical to the contents of .github/workflows/ on the latest commit of any branch!
      # @see https://github.com/orgs/community/discussions/151442
      - name: Push tag
        run: |
          git push origin ${{ inputs.tag_name }}
