name: Main
run-name: 'Main workflow #${{ github.run_number }} triggered by ${{ github.actor }} on ${{ github.ref }}'

on:
  push:
    branches-ignore:
      - dependabot/**
  workflow_dispatch:

# Prevent running builds for the same branch in parallel
# New workflows will cancel existing workflowsâ€¦
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
#  lint:
#    name: Lint
#    uses: ./.github/workflows/npm-lint.yml

  test_maven:
    name: Test Maven Build
    uses: ./.github/workflows/test-maven.yml
    secrets: inherit
